### ISSUE TITLE
apiVersion version is ourfdated since release 0.12.0

### ISSUE THREAD

**Issue by cmoulliard** [jetstack/cert-manager-webhook-example#7]
### Issue

The `apiversion` is outdated since the release `0.12.0` as the apiversion to be used is 
```
apiVersion: cert-manager.io/v1alpha2
```
and not anymore 
```
apiVersion: certmanager.k8s.io/v1alpha1
```

To be fixed within the helm template resource and documented
:  https://github.com/jetstack/cert-manager-webhook-example/blob/master/deploy/example-webhook/templates/pki.yaml#L4

**Remark**: I propose to create a branch in order to handle the apiversion change

**Comment by munnerz** [comment]
Fixed by #11
